### ISSUE TITLE
Dictionary tab behavior when selecting a different package

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#103]
The Dictionary tab (shared with the Package column), is meant to display all defined SymbolDictionaries. 

If you have the Dictionary tab selected and select to a different Project, the Dictionary list is empty.

More generally, it's kind of awkward to have the Dictionary tab in column two, be completely unrelated to the Project column one selection. I feel like there should be some particular project I should select, when I want to work on this code that is not in any existing project.

**Comment by ericwinger** [comment]
Fixed empty dictionary list upon project change here - https://github.com/GemTalk/JadeiteForPharo/commit/c38ca243ddc4c12bf152c83bf9176c35d3c19dd6.

As far as the location of the Dictionary tab, I am open to suggestions but let's open it as a new feature request.  FWIW- Putting a second tab where the projects list is was confusing because of the browser tabs right above it.
