### ISSUE TITLE
"'end" button does not work reliably

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#104]
If you have some text, e.g. type in a workspace
```
aaa
bbb
ccc
```
and your cursor is at the beginning of the bbb row, and you press end, your cursor moves to the end of the ccc row.  Lo these many years and many applications and the end of the bbb row has always up to now been where I would have got to.

It seem to work correctly in a pharo playground...

**Comment by ericwinger** [comment]
This helped complete the fix for earlier bug regarding copying source outside pharo and getting cr's in the text on linux. 
When you type in a pharo workspace, the Enter key will insert a cr but we use lf's to avoid the above-mentioned problem. Now end/home buttons check for the first cr or lf to cover both types of text. 
Not sure I'm super-thrilled with the mixing of end of line characters but it seems to work.
