### ISSUE TITLE
browser should not cutoff panes when opening + open scaled by font if possible

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/JadeiteForPharo#117]
- [x] When opening browser, make sure all panes fit. 
- [x] Open browsers based on font size changed in the Pharo Settings Browser. 
- [x] Reduce unused real estate in tool windows' headers
- [ ] Can the presenter tab be hidden if only one tab is open? 

`JadeiteBrowser>>#initializeWindow:` currently opens browsers at a default initialExtent: of 1600@1000. If that extent is changed to 1200@1000, the resulting browser has the method pane cutoff as in the picture. 

![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/9bc3cda7-7612-402b-a18d-9bf725a2153a)

Ideally, a browser's size wouldn't be initially fixed but would instead open based on the font size selected in Pharo. Pharo's browsers open this way. 

Extra information: 

- `SystemWindow>>initialize` may hold some clues to how scaling and sizing are done. Not sure if some of these api's are available in Spec2 from which JfP windows are built. 

- Scale factor may also be a factor. Not sure quite what it does. 

- Pharo settings browser font selection & scale factor: 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/7d86e74b-287e-45a8-a239-bcc94d4d2c00)

**Comment by dalehenrich** [comment]
I didn't know about scale factor ... a scale factor of 0.7 gives me a usable project browser without having to resort to full screen mode ... and it (bosch/linux) compares favorably with a windows image (rebus/windows) that is not scaled:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/1073f87f-368d-471a-bb4a-d001ef425344)
in fact I have more usable screen real estate inside the bosch pharo window ...

I have yet to spend hours working in (bosch/linux) like I have in (rebus/windows) ...

I agree that that the JfP windows should scale with font size and the scroll bars should not cut off ... since that appears to be the way other pharo windows behave ...

I am still annoyed that even with scaling 1/5 of the window height  is dedicated to the header and footer ... if the shortcut buttons (including the autocommit button at the bottom) could be put on the same line as the menus and the empty gray space between the code pane and the autocommit button was eliminate we'd get a pretty good chunk of the "wasted real estate" back ... 

Now that I'm using the scaling "workaround(?)" I don't feel that this is a super high priority item ...

**Comment by ericwinger** [comment]
Reduced wasted space on browser. 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/5a51e2ae-ae04-4335-9dbb-b17a5b9f5cc0)

**Comment by ericwinger** [comment]
Per checkin, method pane no longer cutoff and browser scaled to font pointSize when opened. 
I don't think it's possible to not display the tab of a notebook presenter when only one tab is shown. If it's really needed, let's open a new issue.

**Comment by ericwinger** [comment]
I made a short video on how JfP responds to Pharo font size changes.  I haven't tested with any other appearance tools in Pharo. 
https://github.com/user-attachments/assets/a335d45f-2862-4372-8c99-cce411b7c649

**Comment by LisaAlmarode** [comment]
I don't like the commit/abort button placement at all, and the project browser is unusable when you change the font size to medium.  The scale factor, while it does make everything blurry, at least does not break the project browser.  The connection browser opens cut off.
