### ISSUE TITLE
Can we have better icons for commit and abort please...

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#42]
They are understandable, but the thumps up and thumbs down have specific meanings that are not the same as commit or abort. 

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/149ae193-7748-4a3c-ad75-a068ebb17392)

**Comment by ericwinger** [comment]
I'm open to any icon changes. The easiest to implement and pick from can be found by inspecting this expression in Pharo. 
```
Smalltalk ui icons
```
I don't think we need to worry about clashing with Pharo icons (at least not yet) as we can think of JfP as a GemStone app implemented in Pharo rather than a Pharo app. My 2 cents.

**Comment by LisaAlmarode** [comment]
Here are the best of the available options, for abort and commit: not great.  I'll let you pick from the list... I kind of like flag or warning and glamorous refresh.
For reference, gbsvw uses a up arrow over a gem and a red x over a gem.

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/f7b46d35-6b9a-42d3-b429-08f9c25e624b)

**Comment by ericwinger** [comment]
```
 I'll let you pick from the list... I kind of like flag or warning and glamorous refresh.
```
I'm fine with any of those. 
Which for abort is your preference? And which for commit?

**Comment by ericwinger** [comment]
Commit and Abort icons improved.
