### ISSUE TITLE
Project Browser Class Pane, Containing Package field

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#59]
- [x] The scroll bars that let you see the whole name cover up the name... there are in fact also vertical scroll bars (though you can't see all the parts), but that is silly for a one line field. (JforD never adds a horizontal scroll bar... you just can't see the full name)

- [x] When you select a different package (and haven't selected a class), it's displaying the previous package, not the selected package. 

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/336a1033-b891-4ea4-ad49-5ed1c75c6cc9)

- [ ] This may or may not be something to fix. If a class name is too long, JforD displays e.g. CustomerOrderDetailC...  JforP just overlaps. This means if the columns are sized just so, you can get missleading results.  I'm not sure I'm personally feeling strongly, but Rowan has some very long class names where the first part is identical.
 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/7ecf8706-78a3-45f7-a79b-943220323d9f)

- [x] I also see that the Class Definition pane was not cleared when I selected the Rowan project and package...

**Comment by ericwinger** [comment]
3rd checkbox - not done. I didn't find an easy way to do hover help like JfD does when list items are longer than the column's width. However, I'm closing the bug anyway because there is a way to see the full name of the list item. Click middle mouse and you'll see the Morphic controls for that widget. In a list, it shows the item's full text, too. See picture. 

Not a great solution, but if a better solution is needed, let's open a new issue. 

![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/abdb8335-72c1-41d2-89e5-7802c9fd7c08)
