### ISSUE TITLE
recompiling a class definition results in `a ClientForwarderSend occurred (error 2336), Message to forward to client, forwarder: 'Class name is already an object. Continue?' receiver: nil`

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#99]
Stack is in attached file ... it looks like interactWithConfirm: failed ... ClientRowarderSend looks like a gci class and not an RSR class 

[2024-04-11_516023019_rowanServerStackDump.txt](https://github.com/GemTalk/JadeiteForPharo/files/14952413/2024-04-11_516023019_rowanServerStackDump.txt)

commitIds:
```
JadeiteForPharo ce29551
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices ef59884
Rowan a7ff49b63
```

**Comment by ericwinger** [comment]
More specifically, if you try to create a class that already exists _but that class is not already selected_ you'll get this walkback.  If you select the class that you're trying to create, no error occurs.

**Comment by ericwinger** [comment]
The problem was indeed in the interaction handler. Believe this is working as of these commits:
JfP: https://github.com/GemTalk/JadeiteForPharo/commit/767930dd7281dfdb1ab5819a11afa7d969b56a0b
Rowan Client Services: [d8025fd](https://github.com/GemTalk/RowanClientServices/commit/d8025fd8e0133a3a9805cb64b00b0040d2c4458c)
